import {initial,worlds,validateCreation,validateSelection,type State,type Kind,type Creation} from '@/lib/domain';
import {boundary,json,identity,input,string,db,roomRow,roomView,ownPieces,event,saveState,hash,token,configured,consumeBudget,fail,runtime,limitedBody,type Row} from '@/lib/server';
import {astra,selectionSchema,creationSchema} from '@/lib/astra';
export const dynamic='force-dynamic';
type Context={params:Promise<{path:string[]}>};
export function GET(request:Request,context:Context){return boundary(async()=>{
 const {path}=await context.params;const user=await identity(path[0]!=='world');
 if(path[0]==='world'){if(!user)return json({user:null,pieces:[],rooms:[],model:configured()});const rooms=(await db().prepare('SELECT r.id,r.kind FROM rooms r JOIN members m ON r.id=m.room WHERE m.user=? ORDER BY r.created DESC LIMIT 30').bind(user.userId).all()).results;return json({user,pieces:await ownPieces(user.userId),rooms,model:configured()});}
 if(path[0]==='rooms'&&path.length===2)return json(await roomView(await roomRow(path[1],user!.userId),user!.userId));
 if(path[0]==='media'&&path.length===2){const media=await db().prepare('SELECT * FROM media WHERE id=?').bind(path[1]).first<{owner:string;mime:string;name:string}>();if(!media)fail('File not found.',404);if(media!.owner!==user!.userId){const roomId=new URL(request.url).searchParams.get('room');if(!roomId)fail('File not found.',404);const row=await roomRow(roomId!,user!.userId);if(!(JSON.parse(row.state) as State).pieces.some(p=>p.media==='media:'+path[1]))fail('File not shared here.',404);}const file=await runtime().BUCKET.get(path[1]);if(!file)fail('File unavailable.',404);return new Response(file!.body,{headers:{'Content-Type':media!.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'",'Content-Disposition':'inline'}});}
 return json({error:'Not found.'},404);
});}
export function POST(request:Request,context:Context){return boundary(async()=>{
 const user=(await identity())!;const {path}=await context.params;
 if(path[0]==='media'&&path.length===1){if(request.headers.get('origin')!==new URL(request.url).origin)fail('Upload from this site.',403);const bytes=await limitedBody(request,8*1024*1024+10000);const form=await new Response(bytes,{headers:{'Content-Type':request.headers.get('content-type')||''}}).formData();const file=form.get('file');if(!file||typeof file==='string'||file.size>8*1024*1024||file.size===0)fail('Choose an image or audio file under 8 MB.');const upload=file as File;const buffer=await upload.arrayBuffer(),b=new Uint8Array(buffer),ascii=(a:number,n:number)=>new TextDecoder().decode(b.slice(a,a+n));let mime='';if(b[0]===137&&ascii(1,3)==='PNG')mime='image/png';else if(b[0]===255&&b[1]===216&&b[2]===255)mime='image/jpeg';else if(ascii(0,4)==='RIFF'&&ascii(8,4)==='WEBP')mime='image/webp';else if(ascii(0,4)==='RIFF'&&ascii(8,4)==='WAVE')mime='audio/wav';else if(ascii(0,4)==='OggS')mime='audio/ogg';else if(ascii(0,3)==='ID3'||b[0]===255&&(b[1]&224)===224)mime='audio/mpeg';else if(b[0]===26&&b[1]===69&&b[2]===223&&b[3]===163&&upload.type==='audio/webm')mime='audio/webm';if(!mime)fail('Use a JPEG, PNG, WebP, MP3, WAV, Ogg, or WebM audio file.');const count=await db().prepare('SELECT COUNT(*) AS n FROM media WHERE owner=?').bind(user.userId).first<{n:number}>();if(count!.n>=40)fail('This demo account has reached its 40-file limit.');const id=crypto.randomUUID();await runtime().BUCKET.put(id,buffer,{httpMetadata:{contentType:mime}});try{await db().prepare('INSERT INTO media (id,owner,mime,name) VALUES (?,?,?,?)').bind(id,user.userId,mime,upload.name.slice(0,160)).run();}catch(e){await runtime().BUCKET.delete(id);throw e;}return json({id});}
 const value=await input(request);
 if(path[0]==='world'&&path.length===1){if(value.action!=='add')fail('Unknown action.');const title=string(value.title,80,'a title'),body=string(value.body,6000,'some context');if(!['memory','curiosity','imagination','offer','sound'].includes(value.kind))fail('Choose a piece type.');if((await ownPieces(user.userId)).length>=40)fail('Your demo World has reached its 40-piece limit.');if(value.media&&!await db().prepare('SELECT id FROM media WHERE id=? AND owner=?').bind(value.media,user.userId).first())fail('That file does not belong to you.',403);const id=crypto.randomUUID();await db().prepare('INSERT INTO pieces (id,owner,title,body,kind,media,created) VALUES (?,?,?,?,?,?,?)').bind(id,user.userId,title,body,value.kind,value.media?'media:'+value.media:null,new Date().toISOString()).run();return json({id});}
 if(path[0]==='rooms'&&path.length===1){if(!Object.hasOwn(worlds,value.kind))fail('Choose a World.');const count=await db().prepare('SELECT COUNT(*) AS n FROM rooms WHERE owner=?').bind(user.userId).first<{n:number}>();if(count!.n>=20)fail('This demo account has reached its 20-room limit.');const id=crypto.randomUUID(),invite=token(),state=initial(value.kind as Kind,value.withSample===true);await db().batch([db().prepare('INSERT INTO rooms (id,owner,kind,invite_hash,state,rev,created) VALUES (?,?,?,?,?,0,?)').bind(id,user.userId,value.kind,await hash(invite),JSON.stringify(state),new Date().toISOString()),db().prepare('INSERT INTO members (room,user,name) VALUES (?,?,?)').bind(id,user.userId,user.displayName)]);return json({room:await roomView(await roomRow(id,user.userId),user.userId),invite});}
 if(path[0]==='rooms'&&path[2]==='join'&&path.length===3){const invite=string(value.invite,100,'the invitation');const row=await db().prepare('SELECT * FROM rooms WHERE id=? AND invite_hash=?').bind(path[1],await hash(invite)).first<Row>();if(!row)fail('That invitation is invalid or has been replaced.',403);if(await db().prepare('SELECT user FROM members WHERE room=? AND user=?').bind(row!.id,user.userId).first())return json(await roomView(row!,user.userId));await db().prepare('INSERT OR IGNORE INTO join_requests (room,user,name) VALUES (?,?,?)').bind(row!.id,user.userId,user.displayName).run();return json({pending:true});}
 if(path[0]==='ai'&&path.length===1){const row=await roomRow(string(value.room,80,'a room'),user.userId);const state=JSON.parse(row.state) as State;if(!configured())fail('Astra needs the server API key. You can still share and write together.',503);if(value.action==='select'){const own=await ownPieces(user.userId);if(!own.length)fail('Add a piece to your private World first.');await consumeBudget(user.userId);const result=await astra('Privately suggest 1–4 of this person’s own pieces that could contribute meaningfully to the shared World. Select only from privatePieces. Explain the specific connection in one sentence each, including complementary knowledge, lived experience or imagination, not just shared keywords. Do not claim a person has agreed to anything. Return zero selections if none are relevant. This result is only shown to its owner.',{privatePieces:own.map(({id,title,body,kind})=>({id,title,body,kind})),sharedPieces:state.pieces,world:worlds[row.kind].question},selectionSchema);return json({selections:validateSelection(result,own)});}
 if(value.action==='create'){if(value.rev!==row.rev)fail('The room has changed. Review its latest pieces and try again.',409);if(!state.pieces.some(p=>p.owner))fail('Bring at least one personal piece into the room first.');const direction=typeof value.direction==='string'?value.direction.trim():'';if(direction.length>1800)fail('Keep your direction under 1,800 characters.');const parent=value.parent?state.creations.find(c=>c.id===value.parent):undefined;if(value.parent&&!parent)fail('That version is no longer available.',409);await consumeBudget(user.userId);const result=validateCreation(await astra('Create one concrete collaborative artifact using these shared pieces, not a generic list of ideas. For story: write a vivid 200–350 word fan branch grounded in the original scene and people’s contributions, explicitly distinguish it from canon. For athlete: make a specific community contribution such as a short script or participatory creative response, never fabricate endorsement. For hospitality: combine people’s observations into a shared discovery or creative experience, with invitations not assumed bookings or commitments. For professional community: produce a useful draft or collaboration proposal based on an actual offer and goal, no clinical advice or sensitive data. When a parent version exists, build on it and the new direction. Credit at least two supplied piece IDs in sources, including at least one personal contribution. The reason must plainly explain what each contribution changed. No markdown fences. Be specific, surprising, useful and concise. Never expose private context not supplied here.',{world:row.kind,sharedPieces:state.pieces,parent,direction},creationSchema),state.pieces);if(!result.sources.some(id=>state.pieces.find(p=>p.id===id)?.owner))fail('The suggestion did not use a personal contribution. Please try again.',502);const creation:Creation={...result,id:crypto.randomUUID(),mode:'live',by:user.displayName,...(parent?{parent:parent.id}:{})};state.creations.push(creation);event(state,`${user.displayName} made a new possibility with Astra.`);const next=await saveState(row,state,value.rev,crypto.randomUUID());return json({room:await roomView(next,user.userId),creation});}fail('Unknown AI action.');}
 return json({error:'Not found.'},404);
});}
export function PATCH(request:Request,context:Context){return boundary(async()=>{
 const user=(await identity())!;const {path}=await context.params;if(path[0]!=='rooms'||path.length!==2)fail('Not found.',404);const v=await input(request),row=await roomRow(path[1],user.userId),state=JSON.parse(row.state) as State;if(['approve','reject','revoke'].includes(v.action)){if(row.owner!==user.userId)fail('Only the room creator can manage access.',403);const target=string(v.user,160,'a member');if(target===row.owner)fail('The room owner cannot be removed.');if(v.action==='approve')await db().batch([db().prepare('INSERT OR IGNORE INTO members (room,user,name) SELECT room,user,name FROM join_requests WHERE room=? AND user=?').bind(row.id,target),db().prepare('DELETE FROM join_requests WHERE room=? AND user=?').bind(row.id,target)]);else if(v.action==='reject')await db().prepare('DELETE FROM join_requests WHERE room=? AND user=?').bind(row.id,target).run();else await db().prepare('DELETE FROM members WHERE room=? AND user=?').bind(row.id,target).run();return json(await roomView(row,user.userId));}const operation=string(v.operationId,80,'an operation ID');if(state.operations.includes(operation))return json(await roomView(row,user.userId));let invite:string|undefined;
 if(v.action==='share'){if(!Array.isArray(v.ids)||v.ids.length===0||v.ids.length>12||v.ids.some((id:unknown)=>typeof id!=='string'))fail('Select between 1 and 12 pieces.');const own=await ownPieces(user.userId);if(v.ids.some((id:string)=>!own.some(p=>p.id===id)))fail('You can only share your own pieces.',403);for(const id of [...new Set(v.ids)] as string[]){if(!state.pieces.some(p=>p.id===id)){const p=own.find(p=>p.id===id)!;state.pieces.push({...p,owner:user.userId,author:user.displayName});}}event(state,`${user.displayName} shared selected pieces.`);}
 else if(v.action==='withdraw'){const p=state.pieces.find(p=>p.id===v.id);if(!p||p.owner!==user.userId)fail('Only the contributor can withdraw this piece.',403);const removed=new Set(state.creations.filter(c=>c.sources.includes(p!.id)).map(c=>c.id));let changed=true;while(changed){changed=false;for(const c of state.creations)if(c.parent&&removed.has(c.parent)&&!removed.has(c.id)){removed.add(c.id);changed=true;}}state.creations=state.creations.filter(c=>!removed.has(c.id));state.pieces=state.pieces.filter(x=>x.id!==p!.id);event(state,`${user.displayName} withdrew a piece and its derived versions. Previously exported copies cannot be recalled.`);}
 else if(v.action==='revise'){const parent=state.creations.find(c=>c.id===v.id);if(!parent)fail('That version is unavailable.',404);state.creations.push({...parent!,id:crypto.randomUUID(),body:string(v.body,10000,'your revision'),mode:'human',by:user.displayName,parent:parent!.id,featured:false});event(state,`${user.displayName} wrote a new branch.`);}
 else if(v.action==='feature'){if(row.owner!==user.userId)fail('Only the room creator can feature a version.',403);if(!state.creations.some(c=>c.id===v.id))fail('Version not found.',404);state.creations=state.creations.map(c=>({...c,featured:c.id===v.id}));event(state,`${user.displayName} featured a community version. This does not make it original canon.`);}
 else if(v.action==='invite'){if(row.owner!==user.userId)fail('Only the room creator can issue invitations.',403);invite=token();event(state,'The room creator replaced the invitation link. Existing members retain access.');}
 else fail('Unknown action.');const next=await saveState(row,state,v.rev,operation,invite?await hash(invite):undefined),view=await roomView(next,user.userId);return json(invite?{room:view,invite}:view);
});}
