'use client';
import {useState} from 'react';
import type {Room,Creation} from '@/lib/domain';
export default function ActivityActions({room,creation,user,change}:{room:Room;creation:Creation;user:string;change:(v:Record<string,unknown>)=>Promise<unknown>}){
 const [message,setMessage]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requests=(room.state.activityRequests||[]).filter(r=>r.creation===creation.id);
 async function act(v:Record<string,unknown>){setBusy(true);setError('');try{await change(v);setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="activity-actions"><p className="eyebrow">FROM POSSIBILITY TO A REAL CONVERSATION</p><h3>Ask. Get an answer. Choose what happens next.</h3><p>A proposal is not a booking or anyone’s commitment. The room creator handles host responses in this demo.</p><label>Your request<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={1800} placeholder="What would you like to do? Include the people, timing or details the host needs."/></label><button className="gold" disabled={busy||!message.trim()} onClick={()=>act({action:'request',id:creation.id,message})}>Send to room host</button>{error&&<p role="alert">{error}</p>}{requests.map(r=><article className="request-card" key={r.id}><p className="eyebrow">{r.status==='reported'?'PARTICIPANT-REPORTED OUTCOME':r.status.toUpperCase()}</p><h4>{r.name} asked</h4><p>{r.message}</p>{r.reply&&<><h4>Room host answered</h4><p>{r.reply}</p></>}{r.outcome&&<><h4>What came back</h4><p>{r.outcome}</p><small>Reported by the participant, not independently confirmed.</small></>}{room.owner&&r.status==='requested'&&<><label>Answer as the room host<textarea maxLength={1800} value={drafts[r.id]||''} onChange={e=>setDrafts({...drafts,[r.id]:e.target.value})} placeholder="Offer a next step, ask for details, or explain why it is not possible."/></label><button className="gold" disabled={busy||!drafts[r.id]?.trim()} onClick={()=>act({action:'reply',id:r.id,reply:drafts[r.id]})}>Send answer</button><button className="text-button" disabled={busy||!drafts[r.id]?.trim()} onClick={()=>act({action:'reply',id:r.id,reply:drafts[r.id],decline:true})}>Decline with explanation</button>{r.user===user&&<small>You are both requester and room host in this solo test.</small>}</>}{r.user===user&&r.status==='answered'&&<button className="gold" disabled={busy} onClick={()=>act({action:'accept',id:r.id})}>Accept this next step</button>}{r.user===user&&r.status==='accepted'&&<><label>What actually happened?<textarea maxLength={1800} value={drafts[r.id]||''} onChange={e=>setDrafts({...drafts,[r.id]:e.target.value})} placeholder="It happened, it changed, or nothing yet. Record the actual outcome."/></label><button className="gold" disabled={busy||!drafts[r.id]?.trim()} onClick={()=>act({action:'report',id:r.id,outcome:drafts[r.id]})}>Return an update</button></>}</article>)}</section>;
}
