'use client';
import {useState} from 'react';
import {ArrowRight,Check,Sparkles,X} from 'lucide-react';
import type {Piece,Room} from '@/lib/domain';
import {mediaUrl} from './encounter-scene';
export type Connection={person:string;name:string;sample:boolean;reason:string;project:string;firstStep:string;yourPieces:string[];theirPieces:string[]};
export default function ConnectionDiscovery({own,room,close,find,start,highlight}:{own:Piece[];room:Room;close:()=>void;find:(ids:string[])=>Promise<Connection[]>;start:(c:Connection)=>Promise<void>;highlight:(ids:string[])=>void}){
 const [ids,setIds]=useState<string[]>([]),[results,setResults]=useState<Connection[]|null>(null),[chosen,setChosen]=useState<Connection|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 async function act(label:string,fn:()=>Promise<void>){setBusy(label);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <section className="orbit-creation connection-discovery" aria-label="Discover a connection"><div className="orbit-creation-top"><small>A DIFFERENT PART OF YOU, WITH EACH PERSON</small><button aria-label="Close connections" disabled={!!busy} onClick={close}><X size={17}/></button></div>
 {chosen?<><small>{chosen.sample?'Fictional solo-demo person':'Participant in this room'} · {chosen.name}</small><h2>{chosen.project}</h2><p className="orbit-work-text">{chosen.reason}</p><div className="connection-pair"><div><small>From your world</small>{chosen.yourPieces.map(id=>{const p=own.find(p=>p.id===id);return p?<article key={id}>{p.media&&p.kind!=='sound'&&<img src={mediaUrl(p)} alt={p.title}/>}<h3>{p.title}</h3><p>{p.body}</p>{p.kind==='sound'&&p.media&&<audio controls src={mediaUrl(p)}/>}</article>:null;})}</div><div><small>From {chosen.name}</small>{chosen.theirPieces.map(id=>{const p=room.state.pieces.find(p=>p.id===id);return p?<article key={id}><h3>{p.title}</h3><p>{p.body}</p></article>:null;})}</div></div><p className="connection-first">Your agent’s first task: {chosen.firstStep}</p><p className="orbit-disclosure">Approving shares the exact pieces above, including attached files, with all members of this room—not only {chosen.name}. The agent uses those shared descriptions to draft the first artifact. It cannot commit either person, contact anyone or book anything. {chosen.sample?'This is a fictional rehearsal, not an accepted human partnership.':'Their agreement to collaborate is still needed.'}</p><div className="orbit-inline-actions"><button disabled={!!busy} onClick={()=>act('Sharing approved pieces and starting the work…',()=>start(chosen))}><Sparkles size={15}/>{busy||'Share these pieces & start a draft'}</button><button disabled={!!busy} onClick={()=>setChosen(null)}>Back</button></div></>:<><h2>{results?'What could begin between you':'Which pieces of you should meet people?'}</h2>{results===null?<><p className="orbit-disclosure">Select up to eight pieces for a private AI search against context others have already shared in this room. Your selections are not shared with people yet.</p><div className="orbit-source-pieces">{own.map(p=><button key={p.id} aria-pressed={ids.includes(p.id)} onClick={()=>setIds(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}>{p.media&&p.kind!=='sound'&&<img src={mediaUrl(p)} alt=""/>}<span>{p.title}</span>{ids.includes(p.id)&&<Check size={12}/>}</button>)}</div><button className="connection-find" disabled={!!busy||ids.length<1||ids.length>8} onClick={()=>act('Finding a useful connection…',async()=>setResults(await find(ids)))}><Sparkles size={16}/>{busy||'Find what we could make possible'}</button></>:<>{results.length===0&&<p>No strong connection from these pieces yet. Try another part of your world or invite someone with different context.</p>}{results.map(c=><button className="connection-result" key={c.person} onClick={()=>{setChosen(c);highlight(c.theirPieces);}}><small>{c.name} · {c.sample?'fictional example':'room participant'}</small><h3>{c.project}</h3><p>{c.reason}</p><span>See which pieces connect <ArrowRight size={14}/></span></button>)}<button className="orbit-back" onClick={()=>setResults(null)}>Choose different pieces</button></>}</>}
 {error&&<p className="orbit-error" role="alert">{error}</p>}{busy&&<p role="status" className="orbit-disclosure">{busy}</p>}
 </section>;
}
