'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,GitBranch,Play,Plus,X,Check} from 'lucide-react';
import type {Room,Creation} from '@/lib/domain';
import {mediaUrl} from './encounter-scene';
import ContributionComposer from './contribution-composer';
import AgentCollaboration from './agent-collaboration';

export default function ContributionWorld({room,user,close,sequence,bring,change,run}:{room:Room;user:string;close:()=>void;sequence:()=>void;bring:()=>void;change:(v:Record<string,unknown>)=>Promise<Room>;run:(task:string,ids:string[])=>Promise<void>}){
 const [focus,setFocus]=useState<string|null>(null),[sources,setSources]=useState<string[]>(['source']),[agents,setAgents]=useState(false),[busy,setBusy]=useState(false);
 const initialFocus=useRef<HTMLButtonElement>(null),rootRef=useRef<HTMLElement>(null);
 function leave(fn:()=>void){const root=rootRef.current;const unsaved=Array.from(root?.querySelectorAll<HTMLElement>('.direct-contribution [contenteditable=true]')||[]).some(el=>el.innerText.trim())||Array.from(root?.querySelectorAll<HTMLInputElement>('.direct-contribution input[type=file]')||[]).some(el=>el.files?.length);if(!unsaved||window.confirm('Leave your unsaved contribution?'))fn();}
 const original=room.state.pieces.find(p=>p.id==='source');
 const sports=room.kind==='fan'||room.kind==='athlete',fiction=room.kind==='story',music=room.kind==='music';
 const current=room.state.creations.find(c=>c.id===focus);
 const byId=(id:string)=>room.state.creations.find(c=>c.id===id);
 const root=(c:Creation)=>{let p=c;const seen=new Set<string>();while(p.parent&&byId(p.parent)&&!seen.has(p.id)){seen.add(p.id);p=byId(p.parent)!;}return p.id;};
 const roots=room.state.creations.filter(c=>!c.parent||!byId(c.parent));
 useEffect(()=>{initialFocus.current?.focus();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[]);
 const heading=sports?'Your response becomes part of the world.':fiction?'A world grows beyond its first telling.':music?'One invitation. Many ways to answer.':'What could you bring to this?';
 const prompts=sports?['A ritual before you begin','The place you learned','A movement or rhythm','Your answer to another fan']:fiction?['A place nobody has drawn','A character’s other memory','The sound of this world','An alternate path through the scene']:music?['A sound you made','An image that answers','A movement or performance idea','A new direction together']:['A perspective','Something you know','An original response','A useful next step'];
 return <section ref={rootRef} className="contribution-world" role="dialog" aria-modal="true" aria-label="Shared contribution world" onKeyDown={e=>{if(e.key==='Escape')leave(close);if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not([hidden]),textarea,[contenteditable="true"],a[href]'));if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}}>
  <header className="commons-header"><button ref={initialFocus} onClick={()=>leave(close)}><ArrowLeft size={17}/> Your worlds</button><span>{room.members.map(m=>m.name).join(' · ')}<small>Room members · saved contributions sync</small></span><button onClick={()=>setAgents(!agents)}>{agents?'Close agents':'People + agents'}</button></header>
  <section className="commons-invitation">{original?.media&&<img src={mediaUrl(original,room)} alt="Original world invitation"/>}<div><small>{sports?'ATHLETE / FAN WORLD':fiction?'AN ORIGINAL FICTIONAL WORLD':music?'MUSIC / A COLLECTIVE WORLD':'A SHARED INVITATION'}</small><h1>{original?.title}</h1><h2>{heading}</h2><p className="original-invitation-text">{original?.body}</p><p className="commons-boundary">{fiction?'Your branch can expand or contradict the fiction. The original stays intact.':sports?'Community responses stay distinct from the athlete’s original invitation. Featuring is not endorsement or permission for commercial use.':'Original contributions, credited to their makers. No commercial reuse permission is implied.'}</p></div></section>
  <div className="commons-actions"><button onClick={()=>{setFocus(null);document.getElementById('respond-to-world')?.scrollIntoView({behavior:'smooth'});}}><Plus size={17}/> Add your response</button><button onClick={()=>leave(bring)}>Bring a piece of your world <ArrowUpRight size={15}/></button><button onClick={()=>leave(sequence)}><Play size={15}/> Assemble a playable sequence</button></div>
  {agents&&<AgentCollaboration room={room} user={user} busy={busy} run={async(task,ids)=>{setBusy(true);try{await run(task,ids);}finally{setBusy(false);}}} change={change}/>}
  <section className="contribution-paths" aria-label="Contribution branches"><header><h2>{fiction?'Paths through this world':'What people are building'}</h2><p>Open a contribution to see its sources or respond. Each branch preserves the work before it.</p></header>
   {!roots.length?<div className="commons-empty"><h3>{sports?'The first response could be yours.':fiction?'The world has room for another perspective.':'There is no finished answer yet.'}</h3><div>{prompts.map(p=><span key={p}>{p}</span>)}</div></div>:<div className="branch-grid">{roots.map(r=><section className="contribution-branch" key={r.id}><small><GitBranch size={13}/> {fiction?'A possible branch':'A response and what it inspired'}</small>{room.state.creations.filter(c=>root(c)===r.id).map(c=><article key={c.id} className={focus===c.id?'selected':''}>{c.parent&&<p className="branch-parent">Builds on {byId(c.parent)?.title}</p>}{c.media&&(c.mediaKind==='sound'?<audio controls src={'/api/media/'+c.media.slice(6)+'?room='+room.id}/>:<img src={'/api/media/'+c.media.slice(6)+'?room='+room.id} alt={c.title}/>)}<div><small>{c.agent?`${c.agent.name} · approved by ${c.agent.approvedBy}`:c.by}{c.featured?' · host-featured':''}</small><h3>{c.title}</h3><p>{c.body.slice(0,230)}{c.body.length>230?'…':''}</p><button onClick={()=>{setFocus(c.id);setSources(c.sources);document.getElementById('respond-to-world')?.scrollIntoView({behavior:'smooth'});}}>Explore & build on this <ArrowUpRight size={14}/></button></div></article>)}</section>)}</div>}
  </section>
  <section id="respond-to-world" className="commons-response"><div><small>{current?'BUILDING ON A CONTRIBUTION':'ANSWERING THE ORIGINAL INVITATION'}</small><h2>{current?.title||'What would you add?'}</h2>{current&&<><p className="full-contribution">{current.body}</p><p>Contributed by {current.by}</p><button onClick={()=>{setFocus(null);setSources(['source']);}}><X size={14}/> Return to the original invitation</button></>}<h3>What shaped your response?</h3><p>Choose the shared pieces you’re building with. This credit travels with your contribution.</p><div className="response-sources">{room.state.pieces.map(p=><button key={p.id} aria-pressed={sources.includes(p.id)} onClick={()=>setSources(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}><span>{p.title}<small>{p.author||"Original source"}</small></span>{sources.includes(p.id)&&<Check size={14}/>}</button>)}</div></div><div>{sources.length>0?<ContributionComposer key={focus||'original'} parent={current?.id} sources={sources} change={async v=>{const next=await change(v);setFocus(next.state.creations.at(-1)!.id);return next;}}/>:<p>Select at least one source to contribute.</p>}<p className="commons-boundary">Image, drawing, sound, knowledge, movement idea or words. Video and finished performance capture are not supported yet.</p></div></section>
 </section>;
}
