'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowRight,ImagePlus,Lock,Mic,Plus,Sparkles,X,Users,Music,ChevronLeft} from 'lucide-react';
import WorldGlobe from './world-globe';
import {worlds,type Piece,type Room,type Kind} from '@/lib/domain';
import {experiences} from '@/lib/experience';

type Props={discoveryPieces?:Piece[];collaboration?:ReactNode;creationFocus?:string|null;creationSources?:string[];onCreation?:(id:string)=>void;own:Piece[];room:Room|null;focus:Piece|null;selected:string[];demo:boolean;busy:string;mode:'mine'|'together';editor:ReactNode;review:ReactNode;editing:boolean;reviewing:boolean;file:File|null;reasons:{id:string;reason:string}[];onFocus:(p:Piece)=>void;onClear:()=>void;onAdd:()=>void;onFile:(file:File)=>void;onDictate:()=>void;onSelect:(id:string)=>void;onReview:()=>void;onSuggest:()=>void;onOpen:()=>void;onExplore:(k:Kind)=>void;onCloseEditor:()=>void;onInvite:()=>void;};
export function mediaUrl(piece:Piece,room?:Room|null){return piece.media?.startsWith('media:')?`/api/media/${piece.media.slice(6)}${room?'?room='+room.id:''}`:piece.media||undefined;}
function SharingTrace({shared}:{shared:boolean}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const draw=()=>{const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.beginPath();ctx.moveTo(0,h*.85);ctx.bezierCurveTo(w*.35,0,w*.7,0,w,h*.6);ctx.setLineDash(shared?[]:[7,8]);ctx.strokeStyle='#dfc68d';ctx.lineWidth=1.5;ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(w-4,h*.6,3,0,Math.PI*2);ctx.fillStyle='#f1dcb0';ctx.fill();};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect();},[shared]);return <canvas ref={ref} className="sharing-trace" aria-label={shared?'This piece is shared in this room':'Proposed sharing path. Not shared yet.'} role="img"/>;}
export default function EncounterScene(p:Props){
 const upload=useRef<HTMLInputElement>(null);
 const [exploring,setExploring]=useState(false),[list,setList]=useState(false),[preview,setPreview]=useState('');
 useEffect(()=>{if(!p.file){setPreview('');return;}const url=URL.createObjectURL(p.file);setPreview(url);return()=>URL.revokeObjectURL(url);},[p.file]);
 const isPrivate=p.focus?p.own.some(x=>x.id===p.focus!.id):true;
 const hero=p.focus||(!p.editing&&!p.reviewing?p.own.find(x=>x.media)||p.own[0]:null);
 const roomTitle=p.discoveryPieces?'Discoverable worlds':p.room?.state.pieces.find(x=>x.id==='source')?.title||'A world to meet';
 const shared=p.discoveryPieces||p.room?.state.pieces||[];
 const works:Piece[]=(p.room?.state.creations||[]).map(c=>({id:'work:'+c.id,title:c.title,body:c.body,kind:c.mediaKind==='sound'?'sound':'imagination',media:c.media||p.room?.state.pieces.find(x=>x.id===c.frames?.[0]?.image)?.media,author:c.by}));
 const proposals:Piece[]=(p.room?.state.agentProposals||[]).filter(x=>x.status==='proposed').map(x=>({id:'work:'+x.id,title:x.draft.title,body:x.draft.body,kind:'offer',author:x.name}));
 const resolve=(pieces:Piece[],room?:Room|null)=>pieces.map(x=>({...x,media:mediaUrl(x,room)}));
 const selectedHero=hero&&p.selected.includes(hero.id);
 const reviewPiece=p.own.find(x=>p.selected.includes(x.id));
 const alreadyShared=!!hero&&shared.some(x=>x.id===hero.id&&(!hero.media||x.media===hero.media));
 const suggestion=p.reasons.find(x=>x.id===hero?.id)?.reason;
 return <main className={`encounter ${p.collaboration?'is-collaborating':''} ${p.editing?'is-composing':''} ${p.reviewing?'is-reviewing':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();p.onFile(e.dataTransfer.files[0]);}}}>
  <header className="encounter-heading"><h1>{p.editing?'Add your context':p.reviewing?'Choose what to share':p.collaboration?roomTitle:'Your context, your choice'}</h1><p>{p.editing?'Saved privately first. Shared only after your review.':p.collaboration?'Contribute yourself, or ask your agent to help.':'Add privately → choose for a room → create together.'}</p></header>
  <div className="private-orbit"><div className="orbit-label"><h2>Your world</h2><p><Lock size={12}/>{p.demo?'Original sample':'Private'}</p></div><WorldGlobe pieces={resolve(p.own)} selected={p.selected} onSelect={p.onFocus}/></div>
  {((!p.collaboration&&(hero||reviewPiece)&&p.room)||(p.discoveryPieces&&p.selected.length>0))&&<SharingTrace shared={!p.discoveryPieces&&alreadyShared}/>}
  <section className="shared-orbit" aria-label="Shared world"><div className="orbit-label"><h2 title={roomTitle}>{roomTitle.length>65?roomTitle.slice(0,62)+'…':roomTitle}</h2><p>{p.discoveryPieces?'Opted-in text · no shared room needed':p.room?'Shared by choice':'Begin an encounter'}</p></div><WorldGlobe pieces={resolve(p.discoveryPieces?shared:[...shared,...works,...proposals],p.room)} selected={p.creationSources||p.room?.state.creations.at(-1)?.sources||[]} onSelect={piece=>piece.id.startsWith("work:")?p.onCreation?.(piece.id.slice(5)):p.onFocus(piece)} shared/>
   <div className="orbit-members">{p.discoveryPieces?<p>Different people. Different possibilities.</p>:p.room?<><span><Users size={13}/>{p.room.members.map(x=>x.name).join(', ')}</span><small>Joined members · not live presence</small></>:<p>A place for what you could make together.</p>}</div>
   <div className="orbit-actions" hidden={!!p.discoveryPieces}><button className="outline" onClick={p.room?p.onOpen:()=>setExploring(true)}>{p.room?'Create here':'Find a world to enter'}<ArrowRight size={15}/></button>{p.room&&<button className="text-button" onClick={p.onInvite}>Invite someone</button>}<button className="text-button" onClick={()=>setExploring(!exploring)}>{exploring?'Close exploration':'Explore other worlds'}</button></div>
  </section>
  <section className="travelling-piece" aria-label={p.editing?'Add a private piece':p.reviewing?'Preview sharing':'Selected piece'}>
   {p.collaboration?p.collaboration:p.editing?<><div className="piece-topline"><span><Lock size={13}/> Only you</span><button aria-label="Close composer" onClick={p.onCloseEditor}><X size={18}/></button></div>{preview&&(p.file?.type.startsWith('audio/')?<audio controls src={preview}/>:p.file?.type.startsWith('image/')?<img className="floating-photo" src={preview} alt="Your unsaved image preview"/>:null)}<div className="in-place-editor">{p.editor}</div></>:p.reviewing?<><button className="text-button" onClick={p.onCloseEditor}><ChevronLeft size={14}/> Back to your world</button>{reviewPiece?.media&&(reviewPiece.kind==='sound'?<audio controls src={mediaUrl(reviewPiece)}/>:<img className="floating-photo" src={mediaUrl(reviewPiece)} alt={reviewPiece.title}/>)}<h2>Share these pieces with this room?</h2><p className="sharing-audience">To all members of <strong>{roomTitle}</strong>. New approved members can see them too. Shared text is sent to AI when someone requests a proposal.</p><div className="in-place-review">{p.review}</div></>:hero?<>
    <div className="piece-topline"><span>{hero.sample?'Original sample':alreadyShared?'Shared in this room':isPrivate?<><Lock size={12}/> Private until you share</>:'Shared in this room'}</span>{p.focus&&<button aria-label="Close selected piece" onClick={p.onClear}><X size={16}/></button>}</div>
    {hero.media?(hero.kind==='sound'?<div className="floating-sound"><Music size={28}/><audio controls src={mediaUrl(hero,isPrivate?null:p.room)}/></div>:<img className="floating-photo" src={mediaUrl(hero,isPrivate?null:p.room)} alt={hero.title}/>):<blockquote className="floating-thought">{hero.body}</blockquote>}
    <h2>{hero.title}</h2>{hero.media&&<p className="piece-context">{hero.body}</p>}
    <div className="agent-whisper"><Sparkles size={23}/><div><small>{suggestion?'Your assistant · suggestion':'Your choice comes first'}</small><p>{suggestion||'A piece of your world. A possibility in another.'}</p></div></div>
    {alreadyShared?<div className="piece-share-actions"><button className="gold" onClick={p.onOpen}>Build with this piece<ArrowRight size={15}/></button><small>The solid trace connects this piece to its shared room.</small></div>:isPrivate?<div className="piece-share-actions"><button className="gold" disabled={!!p.busy} onClick={()=>{if(!selectedHero)p.onSelect(hero.id);p.onReview();}}>{selectedHero?'Preview selected pieces':'Review for this room'}<ArrowRight size={15}/></button><button className="outline" onClick={()=>{if(selectedHero)p.onSelect(hero.id);p.onClear();}}>Keep private</button><small>{p.demo?'Sample only · sign in to bring your own context':'Preview the exact text and attachment before sharing.'}</small></div>:<p className="sharing-audience">{hero.author} · shared with this room</p>}
   </>:<div className="first-piece"><h2>A small piece.<br/>A world of possibility.</h2><p>Bring a photograph, a sound, a memory or something you want to make possible.</p><button className="gold" onClick={p.onAdd}><Plus size={16}/> Add your first piece</button><small>Your context stays private until you choose to share.</small></div>}
  </section>
  <input ref={upload} type="file" hidden accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/webm,audio/ogg,text/plain,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(file)p.onFile(file);e.target.value='';}}/><div className="world-input-dock"><button aria-label="Upload context: image, audio or text file" onClick={()=>upload.current?.click()}><ImagePlus size={24}/></button><button className="dock-prompt" onClick={p.onAdd}>Add your context · paste or write</button><button aria-label="Dictate a private piece" onClick={p.onDictate}><Mic size={22}/></button><button aria-label="Find people to create with" title="Find people to create with" disabled={!!p.busy||!p.own.length||p.demo} onClick={p.onSuggest}><Sparkles size={21}/><span>Find connections</span></button></div>
  <div className="scene-utility"><button onClick={()=>setList(!list)}>{list?'Close piece list':'Browse pieces without motion'}</button><span>{p.busy||'Nothing travels without your approval.'}</span></div>
  {list&&<section className="accessible-pieces" aria-label="Piece list">{p.own.map(x=><button key={x.id} onClick={()=>p.onFocus(x)}>{x.title}<ArrowRight size={14}/></button>)}</section>}
  {exploring&&<section className="world-exploration" aria-label="Explore original worlds"><header><h2>Follow what draws you in.</h2><button aria-label="Close world exploration" onClick={()=>setExploring(false)}><X size={18}/></button></header><div>{(Object.keys(worlds) as Kind[]).map(k=><button key={k} onClick={()=>{setExploring(false);p.onExplore(k);}}><img src={experiences[k].image} alt=""/><span><small>{experiences[k].label}</small><strong>{worlds[k].title}</strong><em>{worlds[k].question}</em></span><ArrowRight size={18}/></button>)}</div></section>}
 </main>;
}
