'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,ArrowRight,Check,GitBranch,ImagePlus,Music,Pause,Play,Plus,Sparkles,Users,X,Expand,Shrink} from 'lucide-react';
import type {Creation,Frame,Room} from '@/lib/domain';
import {applyScenePiece,openingScene,sceneHasMissingSources,scenePieces,sceneSources,type ScenePiece} from '@/lib/living-scene';
import {mediaUrl} from './encounter-scene';
import EditableText from './editable-text';
import ContributionComposer from './contribution-composer';

type Props={room:Room;user:string;current:string|null;onSelect:(id:string|null)=>void;onContext:()=>void;onInvite:()=>void;onBack:()=>void;change:(v:Record<string,unknown>)=>Promise<Room>;arrange:(task:string,ids:string[],parent?:string,scene?:Frame[])=>Promise<void>};
const positions=[[12,27],[86,22],[9,62],[89,65],[12,90],[88,92]];
export default function LivingScene({room,user,current,onSelect,onContext,onInvite,onBack,change,arrange}:Props){
 const [pageSize,setPageSize]=useState(6);
 const [immersive,setImmersive]=useState(false),[dragging,setDragging]=useState(false);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setImmersive(false);};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[]);
 useEffect(()=>{const q=matchMedia('(max-width:800px)');const update=()=>{setPageSize(q.matches?3:6);setPage(0);};update();q.addEventListener('change',update);return()=>q.removeEventListener('change',update);},[]);
 const initial=useRef(openingScene(room)).current;
 const [frames,setFrames]=useState<Frame[]>(initial.frames),[parent,setParent]=useState<Creation|undefined>(initial.parent),[credits,setCredits]=useState<string[]>(initial.credits);
 const [title,setTitle]=useState(initial.parent?.title||room.state.pieces[0]?.title||'Our shared scene');
 const [index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[dirty,setDirty]=useState(false),[pane,setPane]=useState<'contribute'|'agent'|'trace'|'versions'|null>(null);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[file,setFile]=useState<File|null>(null),[compare,setCompare]=useState(false),[page,setPage]=useState(0);
 const [brief,setBrief]=useState(''),[agentIds,setAgentIds]=useState<string[]>(room.state.pieces.slice(0,12).map(p=>p.id));
 const audio=useRef<HTMLAudioElement>(null),picker=useRef<HTMLInputElement>(null),seen=useRef(new Set(room.state.pieces.map(p=>p.id))),revision=useRef(room.rev),priorCurrent=useRef<string|null>(null);
 const proposal=room.state.agentProposals?.find(p=>p.id===current&&p.status==='proposed');
 const selectedVersion=room.state.creations.find(c=>c.id===current);
 const assets=scenePieces(room),visible=assets.slice(page*pageSize,page*pageSize+pageSize),source=room.state.pieces.find(p=>p.id==='source');
 const previewFrames=proposal?.draft.frames||frames;
 const displayFrames=compare?frames:previewFrames;
 const frame=displayFrames[Math.min(index,displayFrames.length-1)]||frames[0];
 const caption=proposal&&!proposal.draft.frames&&!compare?proposal.draft.body.slice(0,500):frame.caption;
 const find=(id:string|null)=>room.state.pieces.find(p=>p.id===id);
 const image=find(frame.image),sound=find(frame.sound);
 const used=sceneSources(displayFrames,proposal&&!compare?proposal.draft.sources:credits);
 const missing=sceneHasMissingSources(room,displayFrames,used,parent);
 const latest=room.state.creations.filter(c=>c.frames?.length).at(-1);
 const unread=latest&&latest.id!==parent?.id;
 const drafts=room.state.agentProposals?.filter(p=>p.status==='proposed')||[];
 useEffect(()=>{if(current===priorCurrent.current)return;priorCurrent.current=current;setPlaying(false);setCompare(false);setIndex(0);if(selectedVersion?.frames){setFrames(selectedVersion.frames.map(f=>({...f})));setCredits(selectedVersion.sources);setParent(selectedVersion);setTitle(selectedVersion.title);setDirty(false);}if(proposal)setPane(null);},[current]);
 useEffect(()=>{if(room.rev===revision.current)return;revision.current=room.rev;const added=room.state.pieces.filter(p=>!seen.current.has(p.id));seen.current=new Set(room.state.pieces.map(p=>p.id));if(added.length){setNotice(added.at(-1)!.author+' added “'+added.at(-1)!.title+'”. Try it in the scene.');setPage(Math.floor((room.state.pieces.length-1)/pageSize));}else setNotice(room.state.events.at(-1)?.text||'The shared work changed.');},[room.rev]);
 useEffect(()=>{if(missing)setPlaying(false);},[missing]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(index<displayFrames.length-1)setIndex(i=>i+1);else{setPlaying(false);setIndex(0);}},frame.seconds*1000);return()=>clearTimeout(timer);},[playing,index,frame.seconds,displayFrames.length]);
 useEffect(()=>{const player=audio.current;if(!player)return;player.currentTime=0;if(playing)player.play().catch(()=>{setPlaying(false);setError('Sound could not start. Press Play again or choose another recording.');});else player.pause();},[playing,index,frame.sound]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function leave(fn:()=>void){if(busy)return;if(dirty&&!window.confirm('Leave your unsaved scene changes? Your shared contributions will stay.'))return;fn();}
 function edit(update:Partial<Frame>){if(proposal)return;setPlaying(false);setFrames(fs=>fs.map((f,i)=>i===index?{...f,...update}:f));setDirty(true);}
 function usePiece(piece:ScenePiece){if(proposal){setNotice('Keep or decline the agent proposal before changing it.');return;}edit(applyScenePiece(frames[index],piece));setCredits(ids=>[...new Set([...ids,...piece.credits])]);setNotice('Trying “'+piece.title+'” in your scene. Save when it feels right.');}
 async function act(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 function choose(id:string){if(dirty&&!window.confirm('Replace your unsaved scene with this version?'))return;setDirty(false);onSelect(id);}
 async function save(){await act('Saving your scene…',async()=>{const next=await change({action:'assemble',title,frames,sources:credits,parent:parent?.id,note:'Composed images, sound and words directly in the shared scene.'});const saved=next.state.creations.at(-1)!;setParent(saved);setCredits(saved.sources);setDirty(false);onSelect(saved.id);setNotice('Saved for this room. Everyone can build on this version.');});}
 function openAgent(){setBrief(room.kind==='story'?'Make a 3-moment atmospheric scene using our supplied images, recordings and perspectives. Give each moment a concise caption. Build on the current scene.':room.kind==='music'?'Arrange our original sounds, images and responses into a short collective sound-and-image piece. Use only available recordings.':'Create a short collective fan ritual from our images, sounds and contributions. Make it playable, not a plan.');setAgentIds([...new Set([...sceneSources(frames,credits),...room.state.pieces.map(p=>p.id)])].slice(0,12));setPane('agent');}
 return <main className={'living-scene '+(playing?'scene-playing ':'')+(immersive?'scene-immersive ':'')+(dragging?'scene-dragging':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{if(!e.dataTransfer.files.length)return;e.preventDefault();setFile(e.dataTransfer.files[0]);setPane('contribute');}}>
  <header className="living-top"><button onClick={()=>leave(onBack)}><ArrowLeft size={17}/> My private world</button><div><span>{room.members.map(m=>m.name).join(' + ')}</span><small>{room.members.length===1?'Only you have joined · invite someone to build together':'Room members · saved changes refresh every few seconds'}</small></div><button onClick={onInvite}><Users size={17}/> Invite someone</button></header>
  <div className="living-title"><small>{room.kind==='story'?'AN ORIGINAL WORLD · COMMUNITY BRANCH':room.kind==='music'?'A COLLECTIVE SOUND & IMAGE WORLD':'AN ATHLETE / FAN CREATION · NOT ENDORSEMENT'}</small><h1>{proposal&&!compare?proposal.draft.title:title}</h1><p>{proposal?'Previewing your agent’s proposal. Nothing is approved yet.':dirty?'Your unsaved arrangement · shared pieces, your changes':parent?'A shared version · keep building on it':'A live sketch from the shared pieces · not yet a saved version'}</p></div>
  <div className="living-stage" aria-label="Compose a shared multimedia scene">
   <svg className="living-traces" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{visible.map((p,i)=><path key={p.id} className={p.credits.some(id=>used.includes(id))?'trace-active':''} d={`M ${positions[i][0]} ${positions[i][1]} Q 50 ${positions[i][1]-20} 50 48`}/>)}</svg>
   {visible.map((p,i)=><button className={'living-fragment '+(p.credits.some(id=>used.includes(id))?'in-scene':'')} key={p.id} draggable={!proposal&&!busy} onDragStart={e=>{e.dataTransfer.setData('application/x-world-piece',p.id);e.dataTransfer.effectAllowed='copy';setDragging(true);}} onDragEnd={()=>setDragging(false)} style={{'--x':positions[i][0]+'%','--y':positions[i][1]+'%','--tilt':(i%2?-5:5)+'deg'} as CSSProperties} onClick={()=>usePiece(p)} aria-label={'Try '+p.title+' in the scene'} disabled={!!busy||!!proposal}>{p.media&&p.kind!=='sound'?<img draggable={false} src={mediaUrl(p,room)} alt=""/>:<div className="fragment-content">{p.kind==='sound'?<Music size={28}/>:<span>{p.body.slice(0,105)}{p.body.length>105?'…':''}</span>}</div>}<strong>{p.title}</strong><small>{p.author||'Original source'}</small></button>)}
   <section className="living-canvas" aria-label="Scene preview" onDragOver={e=>{if(!proposal&&e.dataTransfer.types.includes('application/x-world-piece')){e.preventDefault();e.dataTransfer.dropEffect='copy';}}} onDrop={e=>{const id=e.dataTransfer.getData('application/x-world-piece');if(!id)return;e.preventDefault();e.stopPropagation();setDragging(false);const piece=assets.find(p=>p.id===id);if(piece&&!proposal)usePiece(piece);}}>
    {image?.media?<img key={image.id} className="living-background" src={mediaUrl(image,room)} alt={image.title}/>:<div className="living-no-image">Choose a shared image to set the scene.</div>}
    <div className="living-canvas-shade"/>
    <button className="living-expand" aria-label={immersive?'Return to the shared pieces':'Enter cinema view'} onClick={()=>setImmersive(v=>!v)}>{immersive?<Shrink size={18}/>:<Expand size={18}/>} {immersive?'Back to pieces':'Cinema view'}</button>
    {dragging&&<div className="living-drop-cue">Let this piece become part of the scene.</div>}
    <div className={'living-caption '+(caption.length>140?'caption-long':'')}>{proposal||playing?<p>{caption}</p>:<EditableText value={frame.caption} onChange={v=>edit({caption:v})} label="Words in this scene" placeholder={room.kind==='story'?'What happens here? Write into the scene…':'What do these pieces become together?'} maxLength={500}/>}</div>
    <div className="living-layer-credit">{image&&<span>Image · {image.author||'Original source'}</span>}{sound&&<span><Music size={12}/> {sound.author||'Original source'}</span>}</div>
    {sound?.media&&<audio ref={audio} src={mediaUrl(sound,room)} preload="metadata" onError={()=>{setPlaying(false);setError('This shared recording could not load.');}}/>}
    <button className="living-play" disabled={missing} aria-label={playing?'Pause scene':'Play scene'} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={20}/>:<Play size={20}/>}<span>{playing?'Playing':sound?'Play with sound':'Play · silent scene'}</span></button>
   </section>
   {assets.length>pageSize&&<div className="fragment-pages"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous pieces</button><span>{page+1} / {Math.ceil(assets.length/pageSize)}</span><button disabled={(page+1)*pageSize>=assets.length} onClick={()=>setPage(p=>p+1)}>More pieces</button></div>}
  </div>
  <div className="living-moments" aria-label="Scene moments">{displayFrames.map((f,i)=><button key={i} className={i===index?'active':''} onClick={()=>{setIndex(i);setPlaying(false);}}>{find(f.image)?.media&&<img src={mediaUrl(find(f.image)!,room)} alt=""/>}<span>{i+1} · {f.seconds}s</span>{f.sound&&<Music size={13}/>}</button>)}{!proposal&&<button disabled={frames.length>=12} onClick={()=>{setFrames(fs=>[...fs,{...frames[index],caption:''}]);setIndex(frames.length);setDirty(true);setPlaying(false);}}><Plus size={16}/> Another moment</button>}</div>
  <div className="living-status" role="status">{busy||error||(missing?'A source was withdrawn. Open a current version before saving.':notice||'Click a floating piece to try it. Write directly into the scene. Drop an image or recording to contribute.')} </div>
  {unread&&!proposal&&<button className="living-update" onClick={()=>choose(latest!.id)}>A different shared version is available: {latest!.title} · {latest!.by} <ArrowRight size={16}/></button>}
  <div className="living-actions">
   {proposal?<><button onClick={()=>{setCompare(v=>!v);setIndex(0);setPlaying(false);}}>{compare?'See the proposal':'Compare with my scene'}</button><button onClick={()=>{setPlaying(false);setIndex(0);onSelect(null);}}>Leave undecided & edit my scene</button>{proposal.principal===user?<><button className="living-primary" disabled={!!busy||missing} onClick={()=>act('Keeping the agent’s version…',async()=>{await change({action:'agent-accept',id:proposal.id});setDirty(false);onSelect(proposal.draft.id);if(!proposal.draft.frames){setFrames([{...frames[0],caption:proposal.draft.body.slice(0,500)}]);setCredits(proposal.draft.sources);setParent({...proposal.draft,agent:{principal:proposal.principal,name:proposal.name,approvedBy:room.members.find(m=>m.user===user)?.name||'You'}});setDirty(true);}setNotice('Approved with agent credit. You can now reshape it.');})}><Check size={17}/> Keep this version</button><button disabled={!!busy} onClick={()=>act('Declining proposal…',async()=>{await change({action:'agent-decline',id:proposal.id});onSelect(null);})}>Decline</button></>:<span>Waiting for {proposal.name}’s owner to decide.</span>}</>:<><button onClick={()=>{setFile(null);setPane('contribute');}}><Plus size={18}/> Add your response</button><button onClick={()=>leave(onContext)}><ImagePlus size={18}/> Bring my context</button><button onClick={openAgent} disabled={!!busy}><Sparkles size={18}/> Let our pieces become something</button>{dirty&&<button className="living-primary" disabled={!!busy||missing} onClick={save}><Check size={17}/> Save our scene</button>}</>}
   <button onClick={()=>setPane('trace')}><GitBranch size={17}/> See the traces</button><button onClick={()=>setPane('versions')}>Versions{drafts.length?` · ${drafts.length} pending`:''}</button>
  </div>
  {!proposal&&<div className="living-timing"><button disabled={frame.seconds<=2} onClick={()=>edit({seconds:frame.seconds-1})}>−</button><span>{frame.seconds} seconds in this moment</span><button disabled={frame.seconds>=30} onClick={()=>edit({seconds:frame.seconds+1})}>+</button>{frame.sound&&<button onClick={()=>edit({sound:null})}>Remove sound</button>}{frames.length>1&&<button onClick={()=>{setFrames(fs=>fs.filter((_,i)=>i!==index));setIndex(Math.max(0,index-1));setDirty(true);setPlaying(false);}}>Remove moment</button>}</div>}
  <input ref={picker} hidden type="file" accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/ogg,audio/webm" onChange={e=>{if(e.target.files?.[0]){setFile(e.target.files[0]);setPane('contribute');}e.target.value='';}}/>
  <footer className="living-foot"><button onClick={()=>picker.current?.click()}>Upload an image or sound</button><span>Actual shared assets · no generated audio or video · private context stays outside this scene</span></footer>
  {pane&&<aside className="living-panel" aria-label={pane==='agent'?'Arrange with your agent':pane==='contribute'?'Contribute to this scene':pane==='trace'?'Scene source traces':'Shared versions'}><header><h2>{pane==='agent'?'What could these become?':pane==='contribute'?'Leave something of you here.':pane==='trace'?'Nothing here came from nowhere.':'Ways this world has grown.'}</h2><button aria-label="Close scene panel" disabled={!!busy} onClick={()=>setPane(null)}><X size={22}/></button></header>
   {pane==='contribute'&&<ContributionComposer key={file?.name||'response'} initialFile={file} parent={parent?.id} sources={used.length?used.slice(0,12):['source']} change={async v=>{const next=await change(v);const created=next.state.creations.at(-1)!;setPane(null);setFile(null);setNotice(created.by+' added “'+created.title+'”. It is now shared with this room.');const piece=scenePieces(next).find(p=>p.id==='contribution-'+created.id||p.creation===created.id);if(piece&&!proposal)usePiece(piece);return next;}}/>}
   {pane==='agent'&&<><p>Arrange the selected shared pieces into playable moments. You’ll see and hear the proposal before keeping it.</p><EditableText value={brief} onChange={setBrief} label="Direction for the shared scene" placeholder="A quiet beginning, then let the sound change everything…" maxLength={1800}/><div className="living-agent-pieces">{room.state.pieces.map(p=><button key={p.id} aria-pressed={agentIds.includes(p.id)} onClick={()=>setAgentIds(ids=>ids.includes(p.id)?ids.filter(id=>id!==p.id):[...ids,p.id])}>{p.media&&p.kind!=='sound'?<img src={mediaUrl(p,room)} alt=""/>:<Music size={22}/>}<span>{p.title}<small>{p.author}</small></span>{agentIds.includes(p.id)&&<Check size={15}/>}</button>)}</div><p className="living-permission">One paid agent turn using these shared pieces, your current scene edits, and eligible shared versions. It arranges supplied media; it doesn’t generate new files. {room.state.pieces.some(p=>p.kind==='sound'&&p.media)?'':'No recording has been shared yet, so the result will be silent.'}</p><button className="living-primary" disabled={!!busy||agentIds.length<2||agentIds.length>12||!brief.trim()||sceneSources(frames,credits).some(id=>!agentIds.includes(id))} onClick={()=>act('Your agent is arranging the selected pieces…',async()=>{await arrange(brief,agentIds,parent?.id,frames);setPane(null);})}><Sparkles size={18}/>{busy||'Propose a playable version'}</button><p className="living-permission">Choose 2–12 pieces. Keep the current scene’s sources selected, or remove them from your scene before asking.</p></>}
   {pane==='trace'&&<><p>{proposal?.draft.reason||parent?.reason||'The lit threads show which shared pieces shape this scene.'}</p>{proposal&&!proposal.draft.frames&&<article className="living-source"><h3>Full text of the proposal</h3><p>{proposal.draft.body}</p></article>}{room.state.pieces.filter(p=>used.includes(p.id)).map(p=><article className="living-source" key={p.id}><small>{p.author||'Original source'}{p.sample?' · fictional sample':''}</small><h3>{p.title}</h3><p>{p.body}</p></article>)}{parent&&<p>Builds on “{parent.title}” by {parent.by}. Earlier versions remain intact.</p>}</>}
   {pane==='versions'&&<>{drafts.map(p=><button className="living-version" key={p.id} onClick={()=>{choose(p.id);setPane(null);}}><Sparkles size={17}/><span>{p.draft.title}<small>{p.name} · waiting for approval</small></span></button>)}{room.state.creations.slice().reverse().map(c=><button className="living-version" key={c.id} onClick={()=>{if(c.frames){choose(c.id);setPane(null);}else{const piece=assets.find(p=>p.creation===c.id);if(piece){usePiece(piece);setParent(c);}setPane(null);}}}><GitBranch size={17}/><span>{c.title}<small>{c.by} · {c.frames?c.frames.length+' moments':'contribution'}</small></span></button>)}{!drafts.length&&!room.state.creations.length&&<p>Save the first scene to begin the trail.</p>}</>}
  </aside>}
 </main>;
}
