'use client';
import {useEffect,useRef,useState} from 'react';
import EditableText from './editable-text';
import {Play,Pause,Plus,X,ArrowLeft,ArrowRight,Check,Sparkles,Music,GitBranch,Image as ImageIcon} from 'lucide-react';
import type {Room,Creation,Frame} from '@/lib/domain';
import {mediaUrl} from './encounter-scene';

type Props={room:Room;user:string;close:()=>void;bring:()=>void;change:(v:Record<string,unknown>)=>Promise<Room>;arrange:(task:string,ids:string[])=>Promise<void>};
const empty=():Frame=>({image:null,sound:null,caption:'',seconds:6});
export default function SharedStudio({room,user,close,bring,change,arrange}:Props){
 const versions=room.state.creations.filter(c=>c.frames?.length);
 const initial=versions.at(-1);
 const [frames,setFrames]=useState<Frame[]>(initial?.frames||[empty()]);
 const [parent,setParent]=useState<Creation|undefined>(initial),[title,setTitle]=useState(initial?.title||'Something between us');
 const [note,setNote]=useState(''),[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[elapsed,setElapsed]=useState(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[previewProposal,setPreviewProposal]=useState<string|null>(null);
 const [tab,setTab]=useState<'pieces'|'versions'|'agent'>('pieces'),[brief,setBrief]=useState(''),[ids,setIds]=useState<string[]>([]);
 const audio=useRef<HTMLAudioElement>(null),heading=useRef<HTMLButtonElement>(null);
 const frame=frames[index]||empty(),piece=(id:string|null)=>room.state.pieces.find(p=>p.id===id);
 const imagePiece=piece(frame.image),soundPiece=piece(frame.sound);
 const missing=frames.some(f=>(f.image&&!piece(f.image))||(f.sound&&!piece(f.sound)))||!!parent&&!room.state.creations.some(c=>c.id===parent.id);
 useEffect(()=>{heading.current?.focus();const prior=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prior;};},[]);
 useEffect(()=>{if(missing)setPlaying(false);},[missing]);
 useEffect(()=>{if(!playing)return;const start=performance.now();const timer=setInterval(()=>{const seconds=(performance.now()-start)/1000;setElapsed(seconds);if(seconds>=frame.seconds){if(index<frames.length-1)setIndex(i=>i+1);else{setPlaying(false);setElapsed(0);}}},100);return()=>clearInterval(timer);},[playing,index,frame.seconds,frames.length]);
 useEffect(()=>{const a=audio.current;if(!a)return;a.currentTime=0;if(playing)a.play().catch(()=>{setPlaying(false);setError('Audio playback was blocked. Press Play again or check the file.');});else a.pause();},[playing,index,frame.sound]);
 function edit(v:Partial<Frame>){setPlaying(false);setFrames(all=>all.map((f,i)=>i===index?{...f,...v}:f));setDirty(true);setMessage('');}
 function load(c:Creation){if(dirty&&!window.confirm('Replace your unsaved arrangement with this version?'))return;setPreviewProposal(null);setFrames(c.frames!);setTitle(c.title);setParent(c);setIndex(0);setPlaying(false);setNote('');setDirty(false);setMessage('Loaded this version. Your next save will create a new branch.');}
 async function act(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(previewProposal){setError('Accept the agent proposal first to preserve its authorship, then edit your own branch.');return;}await act(async()=>{const next=await change({action:'assemble',title,frames,parent:parent?.id,note:note||'Assembled shared images, sound and words.'});const saved=next.state.creations.at(-1)!;setParent(saved);setDirty(false);setNote('');setMessage('Saved for everyone in this room. The previous version is unchanged.');});}
 function exit(){if(!dirty||window.confirm('Leave your unsaved arrangement?'))close();}
 const proposals=room.state.agentProposals?.filter(p=>p.draft.frames&&p.status==='proposed')||[];
 return <section className="shared-studio" role="dialog" aria-modal="true" aria-label="Shared creation studio" onKeyDown={e=>{if(e.key==='Escape')exit();if(e.key==='Tab'){const nodes=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,[contenteditable="true"],[tabindex="0"]'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}>
  <header className="studio-header"><button ref={heading} onClick={exit}><ArrowLeft size={17}/> Your worlds</button><span>{room.members.map(m=>m.name).join(' · ')}<small>Shared room · saved changes sync</small></span><button disabled={busy||missing||!!previewProposal||!title.trim()} onClick={save}><Check size={16}/>{busy?'Working…':'Save a new version'}</button></header>
  <div className="studio-intro"><p>MAKE SOMETHING BETWEEN YOU</p><EditableText value={title} onChange={v=>{setTitle(v);setDirty(true);}} label="Creation title" placeholder="Name this creation…" maxLength={80} multiline={false} className="direct-title"/><span>{parent?<>Building on {parent.by}’s version <GitBranch size={13}/></>:'Images. Sound. Words. A shared beginning.'}</span></div>
  {(error||message||missing)&&<p className="studio-notice" role={error||missing?'alert':'status'}>{missing?'A source or parent was withdrawn. Load a current version or remove the missing source before saving.':error||message}</p>}
  <div className="studio-layout"><div className="studio-work">
   <div className={`playable-scene ${playing?'is-playing':''}`} aria-label="Playable creation preview">
    {imagePiece?.media?<img src={mediaUrl(imagePiece,room)} alt={imagePiece.title}/>:<div className="scene-empty"><ImageIcon size={32}/><p>{frame.caption?'A moment in words':'Choose an image from the shared pieces.'}</p></div>}
    {playing?(frame.caption&&<p className="scene-caption">{frame.caption}</p>):<EditableText value={frame.caption} onChange={v=>edit({caption:v})} label="Moment caption" placeholder="Write directly into this moment…" maxLength={500} className="scene-caption scene-editable"/>}
    {soundPiece?.media&&<audio ref={audio} src={mediaUrl(soundPiece,room)} preload="metadata" onError={()=>{setPlaying(false);setError('This sound could not load. Choose another shared sound.');}}/>}
    <div className="scene-credit">{imagePiece&&<span>Image · {imagePiece.author||'Original demo source'}</span>}{soundPiece&&<span>Sound · {soundPiece.author||'Original demo source'}</span>}</div>
   </div>
   <div className="playback-controls"><button aria-label={playing?'Pause sequence':'Play sequence'} disabled={missing} onClick={()=>{if(!playing)setElapsed(0);setPlaying(!playing);}}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><span>Moment {index+1} / {frames.length}</span><progress value={playing?Math.min(elapsed,frame.seconds):0} max={frame.seconds}/><span>{frames.reduce((n,f)=>n+f.seconds,0)} sec</span><small>{soundPiece?'Original shared audio':'Silent moment'}</small></div>
   <div className="moment-strip" aria-label="Sequence moments">{frames.map((f,i)=><button key={i} className={index===i?'active':''} onClick={()=>{setIndex(i);setPlaying(false);setElapsed(0);}}>{piece(f.image)?.media?<img src={mediaUrl(piece(f.image)!,room)} alt=""/>:<ImageIcon size={20}/>}<span>{String(i+1).padStart(2,'0')} · {f.seconds}s {f.sound&&<Music size={12}/>}</span></button>)}<button aria-label="Add moment" disabled={frames.length>=12} onClick={()=>{setFrames([...frames,empty()]);setIndex(frames.length);setPlaying(false);setDirty(true);}}><Plus size={22}/></button></div>
   <div className="moment-edit"><span className="editing-hint">Click the words in the scene to change them.</span><div><button aria-label="Shorten moment" disabled={frame.seconds<=2} onClick={()=>edit({seconds:frame.seconds-1})}>−</button><span>{frame.seconds} seconds</span><button aria-label="Lengthen moment" disabled={frame.seconds>=30} onClick={()=>edit({seconds:frame.seconds+1})}>+</button><button disabled={index===0} aria-label="Move moment earlier" onClick={()=>{const next=[...frames];[next[index-1],next[index]]=[next[index],next[index-1]];setFrames(next);setIndex(index-1);setPlaying(false);setDirty(true);}}><ArrowLeft size={17}/></button><button disabled={index===frames.length-1} aria-label="Move moment later" onClick={()=>{const next=[...frames];[next[index+1],next[index]]=[next[index],next[index+1]];setFrames(next);setIndex(index+1);setPlaying(false);setDirty(true);}}><ArrowRight size={17}/></button><button disabled={frames.length===1} onClick={()=>{setFrames(frames.filter((_,i)=>i!==index));setIndex(Math.max(0,index-1));setPlaying(false);setDirty(true);}}>Remove moment</button></div></div>
   <EditableText value={note} onChange={setNote} label="What did you add or change?" placeholder="Leave a trace of what you changed…" maxLength={1000} className="version-note"/>
  </div><aside className="studio-side"><nav aria-label="Studio tools">{(['pieces','versions','agent'] as const).map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t==='pieces'?'Our pieces':t==='versions'?'Versions':'Our agents'}{t==='agent'&&proposals.length>0&&` (${proposals.length})`}</button>)}</nav>
   {tab==='pieces'&&<><p>Choose what shapes this moment. Only pieces deliberately shared in this room appear here.</p><div className="studio-pieces">{room.state.pieces.map(p=><article key={p.id}>{p.media&&p.kind!=='sound'&&<img src={mediaUrl(p,room)} alt={p.title}/>}<div><small>{p.author||'Original source'}{p.sample?' · fictional sample':''}</small><h3>{p.title}</h3><p>{p.body.slice(0,180)}</p><button onClick={()=>p.media?edit(p.kind==='sound'?{sound:p.id}:{image:p.id}):edit({caption:p.body.slice(0,500)})}>{p.media?p.kind==='sound'?<><Music size={14}/> Use this sound</>:<><ImageIcon size={14}/> Use this image</>:'Use these words'}</button></div></article>)}</div><div className="selected-layers">{frame.image&&<button onClick={()=>edit({image:null})}>Remove image <X size={13}/></button>}{frame.sound&&<button onClick={()=>edit({sound:null})}>Remove sound <X size={13}/></button>}</div><button className="studio-bring" onClick={()=>{if(!dirty||window.confirm('Leave this unsaved arrangement to add a private piece?'))bring();}}><Plus size={17}/> Bring another piece of you</button></>}
   {tab==='versions'&&<><p>Every save is a branch, never an overwrite. Open someone’s version and build on it.</p>{!versions.length&&<p>Your first saved sequence will begin the trail.</p>}{versions.slice().reverse().map(c=><button className="version-entry" key={c.id} onClick={()=>load(c)}><GitBranch size={17}/><span><strong>{c.title}</strong><small>{c.by}{c.agent?' · approved agent arrangement':''}</small><p>{c.reason}</p><small>{c.frames!.length} moments{c.parent?` · builds on ${room.state.creations.find(p=>p.id===c.parent)?.by||'earlier work'}`:''}</small></span></button>)}</>}
   {tab==='agent'&&<><p>Ask your agent to arrange the actual shared media. You can play its proposal before accepting. It cannot create files or share private context.</p><EditableText value={brief} onChange={setBrief} label="Arrangement brief" placeholder="Tell your agent what you imagine…" maxLength={1800} className="direct-body"/><div className="arrangement-sources">{room.state.pieces.map(p=><button key={p.id} aria-pressed={ids.includes(p.id)} onClick={()=>setIds(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}>{p.title}{ids.includes(p.id)&&<Check size={12}/>}</button>)}</div><button disabled={busy||!brief.trim()||ids.length<2||ids.length>12} onClick={()=>act(async()=>{await arrange(brief,ids);setMessage('Your agent’s proposal is visible to this room. Preview it before deciding.');})}><Sparkles size={16}/> Propose a playable arrangement</button><small>One paid AI turn · choose 2–12 shared sources</small>{proposals.map(p=><article className="arrangement-proposal" key={p.id}><small>{p.name} · not approved</small><h3>{p.draft.title}</h3><p>{p.draft.reason}</p><button onClick={()=>{if(dirty&&!window.confirm('Replace your unsaved draft with the agent preview?'))return;setPreviewProposal(p.id);setFrames(p.draft.frames!);setTitle(p.draft.title);setParent(undefined);setIndex(0);setPlaying(false);setDirty(false);setMessage('Previewing an unapproved agent arrangement. Accept below to preserve agent credit.');}}>Preview arrangement</button>{p.principal===user&&<button disabled={busy} onClick={()=>act(async()=>{const next=await change({action:'agent-accept',id:p.id});load(next.state.creations.find(c=>c.id===p.draft.id)!);setMessage('Approved with agent credit. You can now build a human branch from it.');})}><Check size={16}/> Accept with agent credit</button>}</article>)}</>}
  </aside></div>
  <footer className="studio-foot">{room.kind==='story'?'Community fiction · not original canon':room.state.invitation==='create'?'A community creation · not an endorsement':'A shared proposal · not a booking or commitment'}<span>Playback uses supplied images and sound. No media is generated.</span></footer>
 </section>;
}
