'use client';
import {useEffect,useRef,useState} from 'react';
import {Pause,Play,RotateCcw,Music,Lightbulb,HandHeart,MessageCircle} from 'lucide-react';
import type {Piece} from '@/lib/domain';
export default function WorldGlobe({pieces,selected,onSelect,shared=false}:{pieces:Piece[];selected:string[];onSelect:(p:Piece)=>void;shared?:boolean}){
 const host=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),nodes=useRef<(HTMLButtonElement|null)[]>([]);const rotation=useRef({x:-.13,y:.3});const [paused,setPaused]=useState(false);const [hovered,setHovered]=useState(false);const [zoom,setZoom]=useState(1);const drag=useRef<{x:number;y:number}|null>(null);const moved=useRef(false);
 useEffect(()=>{const el=host.current,c=canvas.current;if(!el||!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame=0,last=0;let width=el.clientWidth,height=el.clientHeight;let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const resize=()=>{width=el.clientWidth;height=el.clientHeight;const dpr=Math.min(devicePixelRatio||1,2);c.width=width*dpr;c.height=height*dpr;c.style.width=width+'px';c.style.height=height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);};resize();const observer=new ResizeObserver(resize);observer.observe(el);
 const project=(x:number,y:number,z:number)=>{const a=rotation.current.y,b=rotation.current.x;const xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a);const yy=y*Math.cos(b)-zz*Math.sin(b),z2=y*Math.sin(b)+zz*Math.cos(b);const scale=2.8/(2.8-z2*.45);const radius=Math.min(width*.44,height*.44)*zoom;return {x:width/2+xx*radius*scale,y:height/2+yy*radius*scale,z:z2,scale};};
 const points=Array.from({length:2200},(_,i)=>{const y=1-2*i/2199,r=Math.sqrt(1-y*y),a=i*2.399963;return [Math.cos(a)*r,y,Math.sin(a)*r];});
 const pos=(i:number)=>{const count=Math.max(pieces.length,6);const y=.8-1.6*(i+.5)/count,r=Math.sqrt(1-y*y),a=i*2.399963;return [Math.cos(a)*r,y,Math.sin(a)*r];};
 const draw=(t:number)=>{const dt=Math.min(t-last,40);last=t;if(!paused&&!hovered&&!drag.current&&!reduced)rotation.current.y+=dt*.000065;ctx.clearRect(0,0,width,height);const r=Math.min(width*.44,height*.44)*zoom;const glow=ctx.createRadialGradient(width/2,height/2,r*.2,width/2,height/2,r*1.4);glow.addColorStop(0,shared?'rgba(82,103,111,.10)':'rgba(160,125,65,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,width,height);
 for(let lat=-60;lat<=60;lat+=20){ctx.beginPath();for(let a=0;a<=360;a+=4){const phi=lat*Math.PI/180,theta=a*Math.PI/180,p=project(Math.cos(phi)*Math.cos(theta),Math.sin(phi),Math.cos(phi)*Math.sin(theta));if(a===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}ctx.strokeStyle='rgba(190,172,122,.09)';ctx.lineWidth=.65;ctx.stroke();}
 for(let lng=0;lng<180;lng+=20){ctx.beginPath();for(let a=0;a<=360;a+=4){const phi=a*Math.PI/180,l=lng*Math.PI/180,p=project(Math.cos(phi)*Math.cos(l),Math.sin(phi),Math.cos(phi)*Math.sin(l));if(a===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}ctx.strokeStyle='rgba(177,188,204,.07)';ctx.stroke();}
 for(const xyz of points){const p=project(...xyz as [number,number,number]);ctx.fillStyle=`rgba(${shared?'219,197,148':'219,197,148'},${.13+(p.z+1)*.24})`;ctx.beginPath();ctx.arc(p.x,p.y,p.z>0?1.0:.65,0,Math.PI*2);ctx.fill();}
 const selectedIndices=pieces.map((p,i)=>selected.includes(p.id)?i:-1).filter(i=>i>=0);for(let n=0;n<selectedIndices.length-1;n++){const a=pos(selectedIndices[n]),b=pos(selectedIndices[n+1]);ctx.beginPath();for(let j=0;j<=50;j++){const q=j/50,x=a[0]*(1-q)+b[0]*q,y=a[1]*(1-q)+b[1]*q,z=a[2]*(1-q)+b[2]*q,len=Math.hypot(x,y,z)||1,lift=1+Math.sin(q*Math.PI)*.22,p=project(x/len*lift,y/len*lift,z/len*lift);if(!j)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);}ctx.strokeStyle='rgba(245,209,135,.75)';ctx.lineWidth=1.3;ctx.shadowColor='#e7c574';ctx.shadowBlur=8;ctx.stroke();ctx.shadowBlur=0;}
 pieces.forEach((piece,i)=>{const p=project(...pos(i) as [number,number,number]),node=nodes.current[i];if(node){node.style.transform=`translate(-50%,-50%) translate(${p.x}px,${p.y}px) scale(${.77+(p.z+1)*.13})`;node.style.opacity=String(selected.includes(piece.id)?1:selected.length?.2+(p.z+1)*.22:.33+(p.z+1)*.335);node.style.zIndex=String(Math.round((p.z+1)*30));}});frame=requestAnimationFrame(draw);};frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[pieces,selected,paused,hovered,zoom,shared]);
 return <div className="globe-container"><div className="globe-stage" ref={host} onPointerEnter={()=>setHovered(true)} onPointerLeave={()=>setHovered(false)} onPointerDown={e=>{if((e.target as HTMLElement).closest('button'))return;drag.current={x:e.clientX,y:e.clientY};moved.current=false;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;rotation.current.y+=(e.clientX-drag.current.x)*.006;rotation.current.x+=(e.clientY-drag.current.y)*.003;rotation.current.x=Math.max(-1,Math.min(1,rotation.current.x));drag.current={x:e.clientX,y:e.clientY};moved.current=true;}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><canvas ref={canvas} aria-hidden="true"/>{pieces.map((p,i)=><button key={p.id} ref={el=>{nodes.current[i]=el;}} className={`globe-piece ${selected.includes(p.id)?'lit':''} ${p.media?'has-media':''}`} onClick={()=>onSelect(p)} aria-label={`Open ${p.title}${selected.includes(p.id)?', selected':''}`} style={{left:0,top:0}}>{p.media&&p.kind!=='sound'?<img src={p.media} alt="" draggable={false}/>:<span className="piece-mark">{p.kind==='sound'?<Music size={26}/>:p.kind==='imagination'?<Lightbulb size={26}/>:p.kind==='offer'?<HandHeart size={26}/>:<MessageCircle size={26}/>}</span>}<span className="globe-piece-label"><small>{p.kind}</small>{p.title}</span><i/></button>)}</div><div className="globe-controls"><span>DRAG TO EXPLORE · SELECT A PIECE</span><button aria-label={paused?'Rotate globe':'Pause rotation'} onClick={()=>setPaused(!paused)}>{paused?<Play size={14}/>:<Pause size={14}/>}</button><button aria-label="Reset globe" onClick={()=>{rotation.current={x:-.13,y:.3};setZoom(1);}}><RotateCcw size={14}/></button><input aria-label="Globe zoom" type="range" min=".7" max="1.3" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></div></div>;
}
