export type Kind='story'|'fan'|'music'|'athlete'|'city'|'purpose';
export type Invitation='create'|'connect'|'experience';
export type Piece={id:string;title:string;body:string;kind:string;media?:string|null;author?:string;owner?:string;sample?:boolean};
export type Creation={id:string;title:string;body:string;reason:string;sources:string[];mode:'live'|'sample'|'human';parent?:string;by:string;featured?:boolean;media?:string;mediaKind?:'image'|'sound'};
export type ActivityRequest={id:string;creation:string;user:string;name:string;message:string;status:'requested'|'answered'|'accepted'|'declined'|'reported';reply?:string;outcome?:string;at:string};
export type State={pieces:Piece[];creations:Creation[];events:{text:string;at:string}[];operations:string[];activityRequests?:ActivityRequest[];invitation?:Invitation};
export type Room={id:string;owner:boolean;kind:Kind;rev:number;state:State;members:{name:string;user:string}[];requests?:{name:string;user:string}[]};
export const worlds:Record<Kind,{title:string;label:string;question:string;source:string;sample:Piece}>={
 fan:{title:'How we begin',label:'ATHLETE / FAN PARTICIPATION',question:'What does your first five minutes look or sound like?',source:'Original fictional athlete invitation from runner Jules Morrow: share an image, sound, sketch, movement idea or personal ritual about beginning. Fans can create a collective response, propose a new format, or collaborate. This is not an invitation to impersonate an athlete, use protected material, or claim endorsement. Contributions remain community work unless explicitly featured, which does not grant commercial reuse rights.',sample:{id:'sample-fan',title:'The rhythm of getting ready',body:'I would contribute a 20-second rhythm made from tying shoes and footsteps. Someone else could answer with a photograph or movement sequence.',kind:'offer',author:'Alex · fictional sample',sample:true}},
 music:{title:'A sound we share',label:'MUSIC / A COLLECTIVE RESPONSE',question:'How would you answer this sound?',source:'Original fictional musician invitation: bring a sound you made, a photograph, a movement, a cover concept or a short memory of a place. Collaborators can develop a sound-and-image response. No song recordings or stems are supplied or licensed; do not claim to remix a copyrighted track, perform as a real musician or have artist approval. Work with original contributor-owned material.',sample:{id:'sample-music',title:'A city in three sounds',body:'I record sounds I make with everyday objects. I want to work with someone who thinks in images or movement, so the same rhythm can become something neither of us would make alone.',kind:'offer',author:'Noa · fictional sample',sample:true}},
 story:{title:'The night station',label:'FICTION / A WORLD TO GROW',question:'What if the story went another way?',source:'Original fiction: Elin finds a letter at a lakeside station, addressed to someone who has not arrived. Her sister Ada left before dusk. The station keeper says the waiting room has been empty for years. Fan branches may invent possibilities but must stay separate from the original scene.',sample:{id:'sample-story',title:'Two memories of one evening',body:'I want to write from Ada’s perspective. What if she left a recording instead of a letter? I like stories where two people remember the same night differently.',kind:'imagination',author:'Maya · fictional sample',sample:true}},
 athlete:{title:'Before the crowd',label:'ATHLETE / AN ORIGINAL CONCEPT',question:'What place made you love your sport?',source:'Jules Morrow is a fictional runner whose World includes early morning practice, handwritten training notes and the people who welcomed them. Invitation: share a place or ritual that helped you belong. Nobody may impersonate a real athlete. Community work is not a sponsor deal, endorsement or official statement.',sample:{id:'sample-athlete',title:'Someone ran beside me',body:'The person who slowed down to run beside me mattered more than my first race. I’d love to create a sound-and-story response about people who help us begin.',kind:'memory',author:'Alex · fictional sample',sample:true}},
 city:{title:'The city between us',label:'HOSPITALITY / A SHARED DISCOVERY',question:'Where could this encounter take you?',source:'Original hotel-salon concept beside a lake. The conversation is about places that make us feel at home. Guests share discoveries and propose experiences. No venue availability, booking, travel time or provider agreement is established.',sample:{id:'sample-city',title:'Before the city wakes',body:'I enjoy photographing quiet streets early in the morning. I’d be interested in exploring with someone who notices architecture and the small details I miss.',kind:'curiosity',author:'Sam · fictional sample',sample:true}},
 purpose:{title:'What comes next',label:'COMMUNITY / SOMETHING TO BECOME',question:'What are you trying to make possible?',source:'Original professional community. People share a goal or an actual offer of help, discover a useful connection, and may develop something together. Do not infer commitments or share patient, employment-sensitive or confidential information.',sample:{id:'sample-purpose',title:'A useful first conversation',body:'I have hosted peer-feedback groups. People brought one concrete question and left with a next step. I can share the structure, but a date or mentoring relationship would need agreement.',kind:'offer',author:'Rene · fictional sample',sample:true}}
};
export const samplePieces:Piece[]=[
 {id:'demo-1',title:'The in-between places',body:'Stations, hotel lobbies, the walk home. I’m drawn to the places where people are on their way to becoming something else.',kind:'memory',media:'/world-city.png',sample:true},
 {id:'demo-2',title:'A story you can step into',body:'I want to make a story that changes when someone brings their own perspective. Two people could inhabit the same scene differently.',kind:'imagination',sample:true},
 {id:'demo-3',title:'What hands remember',body:'Sketchbooks, materials, and the knowledge people hold in their hands. I love learning how an object was made.',kind:'curiosity',media:'/sketchbook.png',sample:true},
 {id:'demo-4',title:'Before everyone wakes',body:'There is a different city in the early morning. I like walking without a destination and listening.',kind:'memory',media:'/track.png',sample:true},
 {id:'demo-5',title:'A place at the table',body:'I want to bring people together around what they are trying to create, not only their job titles.',kind:'imagination',sample:true},
 {id:'demo-6',title:'Something I can give',body:'I can help turn a loosely formed idea into a story someone else can understand.',kind:'offer',sample:true}
];
export function initial(kind:Kind,sample:boolean):State{return {pieces:[{id:'source',title:worlds[kind].title,body:worlds[kind].source,kind:'original source',author:'Worlds Together'},...(sample?[worlds[kind].sample]:[])],creations:[],events:[{text:'A new shared world opened.',at:new Date().toISOString()}],operations:[]};}
export function validateSelection(v:any,available:Piece[]){if(!Array.isArray(v?.selections)||v.selections.length>6)throw new Error('The selection was incomplete. Try again.');return v.selections.map((s:any)=>{if(!available.some(p=>p.id===s.id)||typeof s.reason!=='string'||s.reason.length>1000)throw new Error('The model returned an unknown piece. Nothing was shared.');return {id:s.id,reason:s.reason};});}
export function validateCreation(v:any,pieces:Piece[]){for(const key of ['title','body','reason'])if(typeof v?.[key]!=='string'||!v[key].trim()||v[key].length>10000)throw new Error('The suggestion was incomplete. Your work is safe.');if(!Array.isArray(v.sources)||v.sources.length<2||v.sources.some((id:unknown)=>!pieces.some(p=>p.id===id)))throw new Error('The suggestion could not be grounded in the supplied sources.');return {title:v.title as string,body:v.body as string,reason:v.reason as string,sources:[...new Set(v.sources)] as string[]};}
