import type {Kind} from './domain';
export const experiences:Record<Kind,{mode:string;label:string;entry:string;intro:string;action:string;result:string;revise:string;direction:string;image:string;host:string}>={
 fan:{mode:'create',label:'CREATE WITH OTHER FANS',entry:'Athlete / fan participation',intro:'Respond with an original image, sound, ritual, design or performance idea. Build with other fans without pretending the athlete authored or approved it.',action:'Find a creative direction',result:'A COLLECTIVE CREATIVE RESPONSE',revise:'Develop the idea',direction:'What could we create, in what medium?',image:'/track.png',host:'Invitation creator'},
 music:{mode:'create',label:'RESPOND THROUGH SOUND & IMAGE',entry:'Music / fan participation',intro:'Your recording, someone else’s image, a new perspective. Make an original response together, with visible credit.',action:'Find a creative direction',result:'A COLLECTIVE CREATIVE RESPONSE',revise:'Develop the idea',direction:'What could our contributions become?',image:'/lake-dawn.png',host:'Invitation creator'},
 story:{mode:'fiction',label:'IMAGINE TOGETHER',entry:'Co-write a fictional world',intro:'Bring a memory or an imagined possibility into an original scene. Make a new branch, not a claim about real events.',action:'Write a scene together',result:'A FAN-FICTION BRANCH',revise:'Write another version',direction:'What should happen in the story?',image:'/world-city.png',host:'Author / world creator'},
 athlete:{mode:'real',label:'CONNECT THROUGH SPORT & CULTURE',entry:'An athlete-led guest experience',intro:'An original athlete invitation opens a conversation between guests. Turn shared interests into a proposal the programme host can answer.',action:'Shape a shared experience',result:'A GUEST EXPERIENCE PROPOSAL',revise:'Refine this proposal',direction:'What would you like to experience together?',image:'/track.png',host:'Programme host'},
 city:{mode:'real',label:'MEET THROUGH A PLACE',entry:'A hotel gathering & city discovery',intro:'Find a reason to meet, explore or gather. Send the property host a useful request; a proposal is not a booking.',action:'Shape a gathering proposal',result:'A GATHERING PROPOSAL',revise:'Refine this proposal',direction:'What could we do together here?',image:'/world-city.png',host:'Property host'},
 purpose:{mode:'real',label:'HELP EACH OTHER FORWARD',entry:'An ambition meets a capability',intro:'Bring a concrete ambition, a challenge, or something you can offer. Develop a shared next step after choosing to connect.',action:'Shape a shared next step',result:'A COLLABORATION PROPOSAL',revise:'Refine the next step',direction:'What could we help each other make possible?',image:'/sketchbook.png',host:'Community organiser'},
};
