import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const pieces=sqliteTable('pieces',{id:text('id').primaryKey(),owner:text('owner').notNull(),title:text('title').notNull(),body:text('body').notNull(),kind:text('kind').notNull(),media:text('media'),created:text('created').notNull() },t=>[index('pieces_owner').on(t.owner)]);
export const rooms=sqliteTable('rooms',{id:text('id').primaryKey(),owner:text('owner').notNull(),kind:text('kind').notNull(),inviteHash:text('invite_hash').notNull(),state:text('state').notNull(),rev:integer('rev').notNull().default(0),created:text('created').notNull()});
export const members=sqliteTable('members',{room:text('room').notNull(),user:text('user').notNull(),name:text('name').notNull()},t=>[primaryKey({columns:[t.room,t.user]}),index('members_user').on(t.user)]);
export const media=sqliteTable('media',{id:text('id').primaryKey(),owner:text('owner').notNull(),mime:text('mime').notNull(),name:text('name').notNull()});
export const budgets=sqliteTable('budgets',{user:text('user').primaryKey(),window:integer('window').notNull(),count:integer('count').notNull()});
export const joinRequests=sqliteTable('join_requests',{room:text('room').notNull(),user:text('user').notNull(),name:text('name').notNull()},t=>[primaryKey({columns:[t.room,t.user]})]);
export const discoveryProfiles=sqliteTable('discovery_profiles',{user:text('user').primaryKey(),name:text('name').notNull(),pieces:text('pieces').notNull(),enabled:integer('enabled').notNull().default(0),rev:integer('rev').notNull().default(0),updated:text('updated').notNull()});
export const connectionRequests=sqliteTable('connection_requests',{id:text('id').primaryKey(),sender:text('sender').notNull(),recipient:text('recipient').notNull(),senderRev:integer('sender_rev').notNull(),recipientRev:integer('recipient_rev').notNull(),payload:text('payload').notNull(),status:text('status').notNull().default('pending'),room:text('room'),created:text('created').notNull()},t=>[index('connection_sender').on(t.sender),index('connection_recipient').on(t.recipient)]);
